### ISSUE TITLE
api.h file not found

### ISSUE THREAD

**Issue by tlskr** [pgspider/parquet_s3_fdw#2]
When I run `make install`, I get:

`parquet_impl.cpp:26:10: fatal error: 'arrow/api.h' file not found`

This is on MacOS Big Sur 11.3.1.  I have installed Arrow (with `brew install apache-arrow` and `brew install apache-arrow-glib`.

We are excited by the project and would appreciate any help with this.

**Comment by tlskr** [comment]
This has resolved itself.

**Comment by shicholas** [comment]
would love to know how you did this @tlskr, I'm running into the same error.
